[build]
  publish = "public"
  command = "npm run build"

[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "https://photos.reiner.design/*"
  to = "https://reiner.design/:splat"
  status = 302
  force = true
